# -*- coding: utf-8 -*-
"""Customer Sentiment Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13MDhCeCEI7kFt-3pHeCUlMbg1Pf-blYJ
"""

# 1. Install Hugging Face Library
!pip install transformers

# 2. import module
from transformers import pipeline

# 3. Load AI model
print("Model is downloading... plz wait...")
sentiment_analyzer = pipeline("sentiment-analysis")

# 4. Demo review
reviews = [
    "This product is absolutely amazing! I love the battery life.",
    "The quality is terrible, completely a waste of money and time.",
    "The delivery was fast, but the product is just average."
]

# 5. Analysis review with AI
print("\n🔍 Customer review Analysis result:\n")
for review in reviews:
    result = sentiment_analyzer(review)[0]
    print(f"Review: {review}")
    print(f"Sentiment: {result['label']} (Confidence Score: {result['score']:.4f})")
    print("-" * 50)